### ISSUE TITLE
Using VSCode with Remote opens in new window

### ISSUE THREAD

**Issue by sunscreem** [ahuggins/open-on-make#45]
Love this wee package, used if your years.

Seems to now open newly made files in a new window though. I'm using remote - ssh for my development environment. Not sure if that's the issue?

**Comment by ahuggins** [comment]
hmmm, you mean you are SSHed into a server in VS Code, and then when you run a `make` command, which happens on a remote server...it opens in a new window?

Could be a path issue, but I never anticipated such a use case.

Had it worked before? While being SSHed into a machine?

**Comment by sunscreem** [comment]
Hey, Sorry for the slow reply. 

> hmmm, you mean you are SSHed into a server in VS Code, and then when you run a make command, which happens on a remote server...it opens in a new window?

Yes - that correct.

> Had it worked before? While being SSHed into a machine?

Not since I've been using a remote server.

Anything I can do at my end? Could pair up if you wanted?

**Comment by ahuggins** [comment]
Sorry for the delay, work got busy.

My intent with this package was for working locally. Being sshed into a server doesn't sound like local dev to me. And seems like an overly tricky thing to worry about.

I'm open to a PR if you can figure out how to get it to work. But I just don't think it's worth the time/worry about it.

The issue I see, is that the way this package works, it basically is really "low fidelity" in that it just uses php to exec the shell commands for whichever editor the person uses. So which machine the package works on is really determined by where the editor shell command is located.

Given that, I am closing this because I just don't think it's a common use case, and I don't think it's worth the effort.

However, if you open a PR that gets it working, I'll take a look.
