### ISSUE TITLE
Compatibility with nWidart/laravel-modules

### ISSUE THREAD

**Issue by jayadevkv** [ahuggins/open-on-make#6]
Hi,
     when using with nWidart/laravel-modules and using atom editor, it is not working

**Comment by ahuggins** [comment]
Looking at this package, it really "should" not work with Open-on-make. Open-on-make works with the artisan commands that are prefixed with `make:`, the commands with the Laravel-modules are prefixed with `module:` so it really is not designed to open those.

That being said though, it looks like when you create a module with `artisan module:make` it creates a lot of files, like up to 15 or maybe more for different modules. I'm not sure it is helpful to open that many files. If you use Laravel Modules, do you find you often edit all the files after you generate a module?

Also, if you want to work on a PR to add support for Laravel Modules, I'm open to adding it since it shouldn't have an affect on anyone not using Laravel Modules.

**Comment by jayadevkv** [comment]
I was actually referring to the module:make-migration, make-model like commands(single file generating ones). What you said is right about the make:module command. How about opening routes.php by default when creating a module. I ll work on a PR. Great work

**Comment by ahuggins** [comment]
Closing due to being 1.5 years old. Thanks!
